platform :ios, '8.0'
# source 'https://git.coding.net/CocoaPods/Specs.git'

target 'Today-News-iOS' do
  use_frameworks!

  ## 基础库

  # Alamofire - 网络访问工具库
  pod 'Alamofire'

  # MJExtension - JSON 转 Model
  pod 'MJExtension'

  ## 辅助库

  # R.Swift - 资源文件安全使用辅助库
  pod 'R.swift'

  # SnapKit - AutoLayout 辅助库
  pod 'SnapKit'

  # Kingfisher - 为 UIImageView 提供远程图像
  pod 'Kingfisher'

  # SwiftNotificationCenter - 类型安全的通知中心
  pod 'SwiftNotificationCenter'

  ## 控件库

  # DZNEmptyDataSet - 为应用提供空数据集显示功能
  pod 'DZNEmptyDataSet'

  # IQKeyboardManager - 键盘自动管理，防止遮挡（Swift）
  pod 'IQKeyboardManagerSwift'

  # SVProgressHUD - HUD 指示器
  pod 'SVProgressHUD'

  # RKNotificationHub - 为按钮添加提醒标签（Objective-C）
  pod 'RKNotificationHub'

  # MJRefresh - 刷新控件
  pod 'MJRefresh'

  ## 第三方服务

  
end
